language: node_js
node_js:
  - "8"
cache:
  - node_modules
install:
  - npm install
  - npm run compile
script:
  - npm run lint
  - npm test -- tests
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
